In [10]:
# Import the numpy package
import numpy as np

In [11]:
# Use the random function in numpy (  # Random float:  0.0 <= x < 1.0)
np.random.rand()

0.5494196537358697

In [10]:
# Use a simple random function in numpy by setting values to create an array with 3 rows and 4 columns of random data.
np.random.rand(3, 4)

array([[0.84920308, 0.36498684, 0.32061762, 0.53870806],
       [0.17692157, 0.9393475 , 0.43894741, 0.3168346 ],
       [0.02064503, 0.02571844, 0.72473613, 0.82102101]])

In [13]:
# Use a simple random function in numpy by setting values to create an array with 3 sets of data with 4 rows in each and 5 columns of random data.

np.random.rand(3, 4, 5)

array([[[0.76543044, 0.88532958, 0.41823159, 0.69591673, 0.03955615],
        [0.54826296, 0.77945062, 0.29143076, 0.13689701, 0.33165336],
        [0.40617935, 0.6837296 , 0.15354993, 0.3550244 , 0.664394  ],
        [0.42351096, 0.12809097, 0.6593394 , 0.35520456, 0.90765768]],

       [[0.23089892, 0.54948748, 0.16538508, 0.71705481, 0.7949639 ],
        [0.16588265, 0.91959583, 0.08895381, 0.79328366, 0.00745484],
        [0.07746707, 0.38800877, 0.11757479, 0.8249697 , 0.32115389],
        [0.06134637, 0.33968987, 0.04397141, 0.79730144, 0.89980912]],

       [[0.1834846 , 0.53848041, 0.63852182, 0.95843169, 0.56831069],
        [0.24318898, 0.13176002, 0.2409484 , 0.97087578, 0.19076987],
        [0.76234052, 0.05798567, 0.21435505, 0.84069302, 0.70210653],
        [0.81172085, 0.74770495, 0.69600418, 0.90450648, 0.87552459]]])

In [14]:
np.random.rand(3, 4) + 3

array([[3.25912672, 3.86000573, 3.64816683, 3.03381164],
       [3.30956289, 3.93256392, 3.02405371, 3.0050986 ],
       [3.39671306, 3.22835336, 3.10635108, 3.98686132]])

In [18]:
# use a simple random function in numpy to list an array of integers:
np.random.randint(0, 10, 20)

array([3, 9, 1, 3, 4, 9, 6, 9, 4, 7, 1, 1, 6, 1, 4, 7, 2, 2, 8, 9])

In [31]:
# randn: n referring to the normal distribution.
np.random.randn(3)

array([0.61750326, 0.29389352, 0.20851485])

In [34]:
# Return random integers from low (inclusive) to high(exclusive).
Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).
np.random.randint(5, size=20)

array([4, 2, 2, 4, 1, 0, 0, 2, 0, 0, 1, 2, 2, 3, 4, 3, 3, 0, 1, 3])

In [41]:
# Randint creating a 5 by 4 array of ints between 0 and 4: 
np.random.randint(5, size=(5, 4))

array([[0, 1, 4, 3],
       [3, 3, 2, 4],
       [3, 1, 2, 0],
       [2, 0, 4, 1],
       [2, 2, 1, 3]])