In [1]:
import numpy as np

In [21]:
np.random.rand()

0.4789248999228253

In [10]:
np.random.rand(3, 4)

array([[0.84920308, 0.36498684, 0.32061762, 0.53870806],
       [0.17692157, 0.9393475 , 0.43894741, 0.3168346 ],
       [0.02064503, 0.02571844, 0.72473613, 0.82102101]])

In [19]:
np.random.rand(3, 2, 5)

array([[[0.67451766, 0.25548475, 0.0624057 , 0.31926691, 0.1112319 ],
        [0.80226872, 0.88246693, 0.30418935, 0.62623074, 0.90572815]],

       [[0.21006196, 0.1374766 , 0.33108526, 0.44161045, 0.41179679],
        [0.96051381, 0.89548826, 0.45227567, 0.99643125, 0.65365433]],

       [[0.19435063, 0.6332047 , 0.14612323, 0.5140047 , 0.11834556],
        [0.3750687 , 0.93603716, 0.73062967, 0.27436705, 0.70431277]]])

In [13]:
np.random.rand(3, 4) + 3

array([[3.31754787, 3.46680837, 3.25864112, 3.57688869],
       [3.59834097, 3.09400055, 3.97302505, 3.12772289],
       [3.42773293, 3.30061657, 3.26085184, 3.87139404]])

In [18]:
np.random.randint(0, 10, 20)

array([3, 9, 1, 3, 4, 9, 6, 9, 4, 7, 1, 1, 6, 1, 4, 7, 2, 2, 8, 9])

In [31]:
np.random.randn(3)

array([0.61750326, 0.29389352, 0.20851485])

In [34]:
np.random.randint(5, size=20)

array([4, 2, 2, 4, 1, 0, 0, 2, 0, 0, 1, 2, 2, 3, 4, 3, 3, 0, 1, 3])

In [41]:
np.random.randint(5, size=(5, 4))

array([[0, 1, 4, 3],
       [3, 3, 2, 4],
       [3, 1, 2, 0],
       [2, 0, 4, 1],
       [2, 2, 1, 3]])